[package]
name = "rust_dart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-sdk-sys = "2.14.3"

[build-dependencies]
cc = "1.0.71"

[lib]
crate-type = ["cdylib","staticlib"]
