name: rust_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

ffigen:
  output: 'lib/src/cpp.dart'
  headers:
    entry-points:
      - '../rust_dart.h'
dependencies: 
  ffigen: ^3.0.0

